- name: Vault test playbook
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: Show secret from hashicorp vault
      ansible.builtin.debug:
        msg: "hashi_vault: {{ vault_test_var }}"
